name: ci
# Run Rails tests & Jest. If pass & on main, deploy to Heroku.
on: push
jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: yarn install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Install header files for Postgres
        run: sudo apt-get -yqq install libpq-dev

      - name: Increasing the amount of inotify watchers
        # started getting this error around 20-03-01
        # https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers
        run: |
          echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      - name: rails db:setup test test:system
        env:
          PGHOST: localhost
          PGUSER: postgres
          RAILS_ENV: test
          RUBYOPT: "-W:no-deprecated -W:no-experimental"
        run: |
          bin/rails db:setup
          bin/rails test
          bin/rails test:system

      # - name: jest
      #   run: npx jest test/javascript

      - name: heroku deploy
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: tublife
        if: github.ref == 'refs/heads/main' && job.status == 'success'
        run: git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git origin/main:main
